### PR TITLE
Use Fluent UI component library

### LINKED ISSUE #10: Test out Fluent UI Blazor components
Before we start building pages (#5, #6), it would be nice to decide on the component framework (if any). This seems promising to me:
https://www.fluentui-blazor.net/

- Should be enough in terms of components
- Works on .NET 8
- Backed by Microsoft

Result of this task should be: all UI using the newly introduced component library

### PR DESCRIPTION
**Pull request by BenasB**
closes #10

Starts using https://www.fluentui-blazor.net/ for the FrontEnd

image
image
image

### CODE REVIEW

**Comment by 6ar8nas** [comment]
Looks great on Chrome, however on Safari there seem to be some issues and misalignments in comparison to Chrome's version.

Screenshot 2024-05-05 at 10 19 08
Screenshot 2024-05-05 at 10 19 03

**Review by 6ar8nas — CHANGES_REQUESTED** [review]
Safari issues as noted above.

**Comment by BenasB** [comment]
Investigating safari issue

**Review by 6ar8nas — APPROVED** [review]

**Comment by BenasB** [comment]
On old safari (v 15) I seem to have problems loading it as well. Chrome works fine. Let's consider this amount of compatibility enough (latest safari probably should work on all macs).

**Pull request merged**
